### ISSUE TITLE
FixPluginTypesSerialization can cause many moons mods to fail to load.

### ISSUE THREAD

**Issue by TShineCN** [xiaoxiao921/FixPluginTypesSerialization#2]
Hello, I noticed that FixPluginTypesSerialization can cause many moons mods to fail to load.Could you please tell me Is there any other solution besides not using these moons mods?

![1](https://github.com/xiaoxiao921/FixPluginTypesSerialization/assets/54096173/d0797632-217a-4bcf-9625-0266e643e794)

**Comment by xiaoxiao921** [comment]
This has nothing to do with FixPluginTypesSerialization, go to the Lethal Company modding discord, and put your logoutput.log in the help-and-troubleshoot channel so the people there can help you find your problem.
